# Generated by Django 2.0.5 on 2018-06-03 21:18

import django.contrib.postgres.fields.jsonb
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def import_current_rates(apps, schema_editor):
    call_command('import_bittrex_rates')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20180601_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('base_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('datetime', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Exchange')),
            ],
        ),
        migrations.RunPython(import_current_rates, reverse_code=migrations.RunPython.noop),
    ]
