# Generated by Django 2.0.5 on 2018-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
            ],
        ),
    ]
