# Generated by Django 2.0.5 on 2018-06-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180601_2206'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btcrates',
            name='date',
        ),
        migrations.AddField(
            model_name='btcrates',
            name='datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btcrates',
            name='exchange',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.Exchange'),
            preserve_default=False,
        ),
    ]
