version: '3'

services:
    web:
        build: .
        depends_on:
          - db
        env_file:
          - provision/.env.local
        volumes:
          - .:/mitra
          - /var/run/docker.sock:/var/run/docker.sock  #  TODO: move to separate service
        ports:
          - "127.0.0.1:8000:8000"
        restart: always
        stdin_open: true
        tty: true
        networks:
          mitra:
        command: >
            sh -c "
                pip install -r requirements/local.txt &&
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
            "
    db:
        image: postgres:10.1
        environment:
          - docker/.env.local
        ports:
          - "5432:5432"
        volumes:
          - ./provision/db:/docker-entrypoint-initdb.d
          - ./db/data:/var/lib/postgresql/data
        networks:
          mitra:

networks:
    mitra:
