version: '3'

volumes:
    database_data:

services:
    local:
        build: .
        depends_on:
          - db
        env_file:
          - ./.env.local
        volumes:
          - .:/mitra
        ports:
          - "8000:8000"
        command: >
            sh -c "
                pip install -r requirements/local.txt &&
                python manage.py migrate
                python manage.py runserver
            "
    db:
        image: postgres:10.1
        environment:
          - ./.env.local
        ports:
          - "5432:5432"
        volumes:
          - .:/mitra
