version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    env_file:
      - provision/.env.local
    volumes:
      - .:/mitra
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    stdin_open: true
    tty: true
    networks:
      mitra:
    command: >
      sh -c "
        pip install -r requirements/local.txt &&
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:10.1
    env_file:
      - provision/.env.local
    ports:
      - "5432:5432"
    volumes:
      - ./provision/db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    networks:
      mitra:

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
    networks:
      mitra:

  worker:
    build: .
    command: >
      sh -c "
        pip install -r requirements/local.txt &&
        celery -A config worker -l info
      "
    env_file:
      - provision/.env.local
    volumes:
      - .:/mitra
      - ./db/data:/var/lib/postgresql/data
    depends_on:
      - rabbit
      - db
    networks:
      mitra:

  scheduler:
    build: .
    command: >
      sh -c "
        pip install -r requirements/local.txt &&
        celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    env_file:
      - provision/.env.local
    volumes:
      - .:/mitra
      - ./db/data:/var/lib/postgresql/data
    depends_on:
      - worker
    networks:
      mitra:

#  gbot:
#    image: gbot
#    volumes:
#      - .:/mitra
#    networks:
#      mitra:
#    env_file:
#      - provision/temp/.env
#    depends_on:
#      - web

networks:
    mitra:
