version: '3'

volumes:
    database_data:

services:
    staging:
        build: .
        depends_on:
          - db
        env_file:
          - ./.env.staging
        volumes:
          - .:/mitra
        ports:
          - "8000:8000"
        command: >
            sh -c "
                pip3 install -r requirements/staging.txt &&
                python manage.py migrate
                python manage.py runserver 8000
            "
    db:
        image: postgres:10.1
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
        ports:
          - "5432:5432"
