# Generated by Django 2.0.5 on 2018-06-03 21:33
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models

from apps.order.models import Exchange
from apps.profile_app.models import Account


def create_bittrex_account(apps, schema_editor):
    dummy_user = User.objects.create(
        username='dummy',
        is_active=False
    )
    Account.objects.create(
        user=dummy_user,
        exchange=Exchange.objects.get(name='bittrex'),
        is_active=True
    )
    return 'Done Dummy user for Bittrex was successfully created.'


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(create_bittrex_account, reverse_code=migrations.RunPython.noop),
    ]
