# Generated by Django 2.0.5 on 2018-06-01 22:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

from apps.order import constance
from apps.order.models import Exchange


def create_exchanges_instances(apps, schema_editor):
    for exchange, exchange_title in constance.EXCHANGES_CHOICES:
        is_active = False
        if exchange == 'bittrex':
            is_active = True
        Exchange.objects.create(
            name=exchange,
            is_active=is_active
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bittrex', 'Bittrex'), ('binance', 'Binance'), ('bitfinex', 'Bitfinex'), ('bitfinex', 'Bitfinex'), ('okcoin', 'Okcoin')], max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_exchanges_instances, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, help_text='Remote unique identifier', null=True)),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=5)),
                ('pair', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
