# Generated by Django 2.0.5 on 2018-11-06 23:09

from django.db import migrations, models
import django.db.models.deletion

from apps.order import constants
from apps.order.models import Exchange


def create_exchanges_instances(apps, schema_editor):
    for exchange, exchange_title in constants.EXCHANGES_CHOICES:
        Exchange.objects.create(name=exchange, is_active=False)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.Account'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Exchange'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uuid'], name='order_order_uuid_411e74_idx'),
        ),
        migrations.RunPython(create_exchanges_instances, migrations.RunPython.noop)
    ]
