# Generated by Django 2.0.5 on 2018-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181106_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('bittrex', 'Bittrex')], max_length=255, unique=True),
        ),
    ]
