# Generated by Django 2.0.5 on 2018-06-06 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180601_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('bittrex', 'Bittrex'), ('binance', 'Binance'), ('bitfinex', 'Bitfinex'), ('okcoin', 'Okcoin')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
