# Generated by Django 2.0.5 on 2018-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('bittrex', 'Bittrex'), ('poloniex', 'Poloniex')], max_length=255, unique=True),
        ),
    ]
