# Generated by Django 2.0.5 on 2019-01-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181202_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Exchange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, help_text='Remote unique identifier', max_length=255, null=True),
        ),
    ]
