# Generated by Django 2.0.5 on 2019-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190102_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pair',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('pair', 'exchange')},
        ),
    ]
