# Generated by Django 2.0.5 on 2018-08-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategies'},
        ),
    ]
