# Generated by Django 2.0.5 on 2018-12-02 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategy_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
