# Generated by Django 2.0.5 on 2018-05-25 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bittrex', 'Bittrex'), ('binance', 'Binance')], max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, help_text='Remote unique identifier', max_length=255, null=True)),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=5)),
                ('pair', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
