# Generated by Django 2.0.5 on 2018-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180508_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
