# Generated by Django 2.0.5 on 2018-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180531_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, help_text='Remote unique identifier', null=True),
        ),
    ]
