# Generated by Django 2.0.5 on 2018-05-08 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
